# Generated by Django 5.0 on 2023-12-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadedfile_file_url_uploadedfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_url',
        ),
    ]
